version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - flask-redis
      - flask-database

  flask-redis:
    image: redis:latest
    ports:
      - 6379:6379

  flask-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flaskdb
    ports:
      - 5432:5432
